export const GET_VENUE_REQUESTED = 'GET_VENUE_REQUESTED';
export const GET_VENUES_REJECTED = 'GET_VENUES_REJECTED';
export const GET_VENUES_FULFILLED = 'GET_VENUES_FULFILLED';
export const GET_LOCATIONS_REQUESTED = 'GET_LOCATIONS_REQUESTED';
export const GET_LOCATIONS_REJECTED = 'GET_LOCATIONS_REJECTED';
export const GET_LOCATIONS_FULFILLED = 'GET_LOCATIONS_FULFILLED';
